version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: guilherme
      MONGO_INITDB_ROOT_PASSWORD: gui321
      MONGO_INITDB_DATABASE: chat
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017